/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_anybar.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "focusdir.c"
#include "focusfollowmouse.c"
#include "focusmaster.c"
#include "focusurgent.c"
#include "fullscreen.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "maximize.c"
#include "movestack.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "riodraw.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shiftboth.c"
#include "shifttag.c"
#include "shiftviewclients.c"
#ifdef XINERAMA
#include "sortscreens.c"
#endif // XINERAMA
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "toggletopbar.c"
#include "vanitygaps.c"
#include "winview.c"
#include "zoomswap.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_monocle.c"
#include "layout_tile.c"

