/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_anybar.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "fakefullscreenclient.h"
#include "floatpos.h"
#include "focusdir.h"
#include "focusfollowmouse.h"
#include "focusmaster.h"
#include "focusurgent.h"
#include "fullscreen.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "maximize.h"
#include "movestack.h"
#include "nomodbuttons.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "riodraw.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shiftboth.h"
#include "shifttag.h"
#include "shiftviewclients.h"
#ifdef XINERAMA
#include "sortscreens.h"
#endif // XINERAMA
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "toggletopbar.h"
#include "vanitygaps.h"
#include "winview.h"
#include "zoomswap.h"
/* Layouts */
#include "layout_monocle.h"
#include "layout_tile.h"

